// AUTOGENERATED FILE - DO NOT EDIT.
//
// This file has been automatically generated by FrankenPHP extension generator
// and should not be edited as it will be overwritten when running the
// extension generator again.
//
// You may edit the file and remove this comment if you plan to manually maintain
// this file going forward.

#ifndef _{{.HeaderGuard}}
#define _{{.HeaderGuard}}

#include <php.h>
#include <stdint.h>

extern zend_module_entry {{.BaseName}}_module_entry;

{{if .Constants}}
/* User defined constants */{{end}}
{{range .Constants}}#define {{.Name}} {{.CValue}}
{{end}}
#endif
