---
name: Deploy Docs
on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "README.md"
      - "CONTRIBUTING.md"
      - "install.ps1"
      - "install.sh"
permissions: {}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  deploy:
    runs-on: ubuntu-slim
    steps:
      - name: Trigger website deployment
        env:
          GH_TOKEN: ${{ secrets.WEBSITE_DEPLOY_TOKEN }}
        run: gh api repos/dunglas/frankenphp-website/actions/workflows/hugo.yaml/dispatches -f ref=main
